import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  console.log("PROPS?", props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Ignoble prizes</h1>
        <div>
          {props.years.map((year) => (
            <button key={year}>{year}</button>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  console.log("HELLO??");
  const response = await fetch("https://ignoble-api.onrender.com/years");
  const data = await response.json();
  console.log(data.years);
  return {
    props: {
      years: data.years,
    }, // will be passed to the page component as props
  };
}
